# Generated by Django 4.0 on 2022-02-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
